version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    environment:
      - 'SERVER_NAME=localhost'

#  minio:
#    image: 'minio/minio:latest'
#    command: 'server --console-address ":9001" /data'
#    environment:
#      - 'MINIO_ROOT_USER=root'
#      - 'MINIO_ROOT_PASSWORD=Strong#Pass#2022'
#    ports:
#      - '9000:9000'
#      - '9001:9001'
